import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local'; // ✅ Import for local fonts
import './globals.css';
import Header from './_components/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const mabryPro = localFont({
  src: [
    {
      path: '../../fonts/mabry-pro/MabryPro-Black.woff2',
      weight: '900',
      style: 'bold',
    },
    {
      path: '../../fonts/mabry-pro/MabryPro-Bold.woff',
      weight: '700',
      style: 'semibold',
    },
    {
      path: '../../fonts/mabry-pro/MabryPro-Regular.woff',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-mabry',
});

const exo2 = localFont({
  src: [
    { path: '../../fonts/exo2/Exo2-Bold.ttf', weight: '700', style: 'bold' },
    {
      path: '../../fonts/exo2/Exo2-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-exo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mabryPro.variable} ${exo2.variable} antialiased`}
      >
        <div className="fixed top-0 w-full z-90">
          <Header />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
